unbind-key C-b
unbind-key C-o
set -g prefix C-o
bind-key C-o send-prefix

bind r source-file ~/.tmux.conf

set-window-option -g mode-keys vi
if-shell "which putclip" '\
  bind-key -t vi-copy y copy-pipe "iconv -s SJIS | putclip"; \
  bind-key -t vi-copy enter copy-pipe "iconv -s -t SJIS | putclip"; \
'

set-option -g base-index 1

bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g status-fg black
set -g status-bg yellow
set -g status-position top
# setw -g window-status-current-fg   red
# setw -g window-status-current-attr bright
set-option -sg escape-time 10
set-option -g focus-events on

set-option -g status-bg "colour45"
set-window-option -g window-status-current-format "#[fg=colour255,bg=colour27,bold] #I: #W #[default]"

# tmux-thumbs
# set -g @plugin 'fcsonline/tmux-thumbs'
run-shell ~/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux

run -b '~/.tmux/plugins/tpm/tpm'

